num_workers = 2
#cache_size = 500000
#log_level = "trace"
#log_level = "debug"

[origin]
host = "localhost"
port = 5432
user = "postgres"
#database = "origin"
database = "pagila"
#database = "conta_azul"

#host = "ep-orange-river-afs4ceae.c-2.us-west-2.aws.neon.tech"
#port = 5432
#user = "neondb_owner"
#database = "neondb"
#ssl_mode = "require"

[cache]
host = "localhost"
port = 7654
user = "postgres"
database = "cache"

[cdc]
#publication_name = "sakila_pub"
#slot_name = "sakila_slot"
publication_name = "pub_test"
slot_name = "slot_test"

[listen]
socket = "127.0.0.1:6432"

[metrics]
socket = "127.0.0.1:9090"
